import {z} from 'zod';
import reference from './reference.json';
export const statuses=['NEEDS_DECISION','DEFINED','BLOCKER','NOT_APPLICABLE'] as const;
export const canvases=reference.canvases;
export const tables=reference.tableSchemas;
const text=z.string().max(100000);
const iso=z.string().datetime();
const row=z.object({id:text.min(1)}).catchall(text);
export const schema=z.object({schemaVersion:z.literal('3.0'),document:z.object({id:text.min(1),createdAt:iso,updatedAt:iso,lastReviewed:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}),agent:z.object({id:text.min(1),name:text,version:text,environment:text,owner:text,runtime:text,purpose:text,autonomyLevel:z.enum(['L0','L1','L2','L3','L4','L5']),lifecycle:z.enum(['DRAFT','DEVELOPMENT','EVALUATION','APPROVED','PRODUCTION','DEPRECATED','RETIRED']),may:text,never:text}),decisions:z.array(z.object({id:text.min(1),canvas:text,title:text,guidance:text,decision:text,status:z.enum(statuses),notes:text,updatedAt:iso})).max(2000),inventories:z.record(z.array(row).max(1000)),extensions:z.record(z.unknown()).default({})}).superRefine((a,ctx)=>{for(const [name,rows] of Object.entries(a.inventories)){const table=(tables as Record<string,{columns:(string|string[])[][]}>)[name];if(!table)continue;for(const r of rows){for(const key of Object.keys(r)){if(key!=='id'&&!table.columns.some(c=>c[0]===key))ctx.addIssue({code:'custom',message:'Unknown resource field: '+key});}for(const c of table.columns){if(c[2]==='select'&&r[String(c[0])]&&!(c[3] as string[]).some(o=>o.toUpperCase().replace(/ /g,'_')===r[String(c[0])].toUpperCase().replace(/ /g,'_')))ctx.addIssue({code:'custom',message:'Invalid resource category'});}}}});
export type AgentArchitecture=z.infer<typeof schema>;
export type Decision=AgentArchitecture['decisions'][number];
export const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export function createArchitecture():AgentArchitecture{const now=new Date().toISOString();return {schemaVersion:'3.0',document:{id:crypto.randomUUID(),createdAt:now,updatedAt:now,lastReviewed:localDate()},agent:{id:crypto.randomUUID(),name:'',version:'',environment:'Development',owner:'',runtime:'',purpose:'',autonomyLevel:'L0',lifecycle:'DRAFT',may:'',never:''},decisions:canvases.flatMap(c=>('decisions'in c?c.decisions||[]:[]).map((d,i)=>({id:`${c.id}.${i}`,canvas:c.id,title:d[0],guidance:d[1],decision:'',status:'NEEDS_DECISION' as const,notes:'',updatedAt:now}))),inventories:Object.fromEntries(Object.keys(tables).map(k=>[k,['safety','security'].includes(k)?['Prompt injection','Data exfiltration','Excessive agency','Hallucinated actions','Tool abuse','Sensitive data exposure','Cross-tenant leakage','Memory poisoning','Agent impersonation','Model/tool supply-chain risk'].map(title=>({id:crypto.randomUUID(),[k==='safety'?'risk':'threat']:title,status:'NEEDS_DECISION'})):[]])),extensions:{}};}
export function parseArchitecture(raw:string):AgentArchitecture{if(raw.length>5000000)throw Error('File exceeds 5 MB');const value:unknown=JSON.parse(raw);const legacy=z.object({schemaVersion:z.literal('2.0'),application:z.literal('Agent Architecture Canvas Pack'),fields:z.record(text),tables:z.record(z.array(z.record(text))),activeTab:text.optional(),exportedAt:text.optional()}).safeParse(value);
let source=value;
if(legacy.success){const a=createArchitecture(),f=legacy.data.fields;for(const [key,id] of Object.entries({name:'meta-agent',owner:'meta-owner',version:'meta-version',environment:'meta-environment',runtime:'meta-runtime',may:'overview-may',never:'overview-never',purpose:'overview-objective'})){(a.agent as Record<string,string>)[key]=f[id]||'';}a.agent.autonomyLevel=(f['overview-autonomy']?.slice(0,2)||'L0') as AgentArchitecture['agent']['autonomyLevel'];a.document.lastReviewed=f['meta-reviewed']||localDate();a.decisions.forEach(d=>{const i=d.id.split('.')[1];d.decision=f[`${d.canvas}-decision-${i}`]||'';d.status=({'Defined':'DEFINED','Blocker':'BLOCKER','Needs decision':'NEEDS_DECISION'} as Record<string,Decision['status']>)[f[`${d.canvas}-status-${i}`]]||'NEEDS_DECISION';});for(const [k,rows]of Object.entries(legacy.data.tables))a.inventories[k]=rows.map(r=>({...r,id:crypto.randomUUID()}));source=a;}
const a=schema.parse(source);
for(const [name,rows] of Object.entries(a.inventories)){
 const table=(tables as Record<string,{columns:(string|string[])[][]}>)[name];
 if(!table){if(name==='integrations')continue;throw Error('Unknown inventory: '+name);}
 for(const r of rows){for(const key of Object.keys(r)){if(key!=='id'&&!table.columns.some(c=>c[0]===key))throw Error('Unknown resource field: '+key);}
 for(const col of table.columns){if(col[2]!=='select'||!r[String(col[0])])continue;const options=col[3] as string[];const v=r[String(col[0])];const matched=options.find(o=>o.toUpperCase().replace(/ /g,'_')===v.toUpperCase().replace(/ /g,'_'));if(!matched)throw Error('Invalid '+String(col[0])+': '+v);if(legacy.success)r[String(col[0])]=matched.toUpperCase().replace(/ /g,'_');}}
}
// Remove only blank, unresolved generated additions; never discard entered work or blockers.
const previousCounts:Record<string,number>={definition:14,identity:12,evaluation:15,delegation:9,runtime:15,observability:18,readiness:16};
a.decisions=a.decisions.filter(d=>{const c=canvases.find(c=>c.id===d.canvas);const count=c&&'decisions'in c?(c.decisions||[]).length:0;const index=Number(d.id.slice(d.canvas.length+1));const redundant=d.id===`${d.canvas}.${index}`&&index>=count&&index<(previousCounts[d.canvas]||0);return !redundant||d.status!=='NEEDS_DECISION'||!!d.decision.trim()||!!d.notes.trim();});
if(!a.decisions.length)throw Error('Missing architecture decisions');const ids=[...a.decisions.map(d=>d.id),...Object.values(a.inventories).flat().map(r=>r.id)];if(new Set(ids).size!==ids.length)throw Error('Duplicate IDs');if(a.decisions.some(d=>!canvases.some(c=>c.id===d.canvas)))throw Error('Unknown canvas');return a;}
