import fs from 'node:fs';
const p='src/domain/reference.json',r=JSON.parse(fs.readFileSync(p));
const extras={definition:['Responsibilities','Explicit non-responsibilities','Inputs','Outputs','Human involvement','Ownership'],identity:['Tenant isolation','User delegation','Approval requirements','Agent-to-agent invocation'],evaluation:['Task success','Tool argument accuracy','Hallucination rate','Safety tests','Adversarial tests','Latency','Cost','Human feedback'],delegation:['Recursive delegation allowed?','Audit ownership','Failure ownership'],runtime:['Runtime/platform','Region','Internet egress','Model access','Secret management','Memory backend','Rollback strategy'],observability:['Agent run tracing','Model calls','Tool calls','Policy decisions','Memory retrieval','Agent delegation','Human approvals','Errors','Token consumption','Cost','Latency','Outcome/success'],readiness:['Identity & Access','Tools','Memory','Safety','Runtime','SLOs','Ownership','Runbooks']};
for(const c of r.canvases)for(const title of extras[c.id]||[])c.decisions.push([title,`Define ${title.toLowerCase()}, constraints, ownership and review evidence.`]);
r.canvases.find(c=>c.id==='observability').decisions.find(d=>d[0]==='Correlation')[1]='Propagate agent_run_id, agent_id, agent_version, session_id, trace_id, caller_id, tool_id, model_id. Define tenant boundaries.';
const fields={tools:[['idempotent','Idempotent?','select',['','Yes','No']],['timeout','Timeout','text',''],['retry','Retry policy','text',''],['classification','Data classification','text',''],['callers','Allowed callers','text',''],['notes','Notes','textarea','']],memory:[['notes','Notes','textarea','']],safety:[['status','Status','select',['NEEDS_DECISION','DEFINED','BLOCKER','NOT_APPLICABLE']],['residual','Residual risk','select',['','Low','Medium','High','Critical']]],delegation:[['identity','Identity propagation','text',''],['timeout','Maximum timeout','text','']],security:[['surface','Attack surface','text',''],['boundary','Trust boundary','text',''],['status','Status','select',['NEEDS_DECISION','DEFINED','BLOCKER','NOT_APPLICABLE']]]};
for(const [k,v]of Object.entries(fields))r.tableSchemas[k].columns.push(...v);
r.tableSchemas.integrations={title:'Integration inventory',columns:[['name','Integration','text',''],['purpose','Purpose','text',''],['owner','Owner','text',''],['notes','Notes','textarea','']]};
fs.writeFileSync(p,JSON.stringify(r,null,2));
