import guidanceData from './domain/guidance.json';
import React from 'react';
import reference from './domain/reference.json';
import {statuses,type Decision} from './domain/model';
const autonomyLabels:Record<string,string>={'L0':'L0 — Answer only','L1':'L1 — Recommend','L2':'L2 — Prepare action','L3':'L3 — Execute reversible','L4':'L4 — Execute external','L5':'L5 — High-impact autonomous'};
export const tone=(v:string)=>({NEEDS_DECISION:'amber',DEFINED:'green',BLOCKER:'red',NOT_APPLICABLE:'gray'}[v]||(reference.colorMap as Record<string,string>)[autonomyLabels[v]||v]||Object.entries(reference.colorMap).find(([k])=>k.toUpperCase().replace(/ /g,'_')===v)?.[1]||'gray');
export function Field({label,value,onChange,options,type='text',placeholder=''}:{label:string,value:string,onChange:(v:string)=>void,options?:readonly string[],type?:string,placeholder?:string}){return <label>{label}{options?<select className={'tone-'+tone(value)} value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v} value={v}>{autonomyLabels[v]||v}</option>)}</select>:<input type={type} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
export function DecisionCard({d,onChange}:{d:Decision,onChange:(d:Decision)=>void}){const entry=(guidanceData as Record<string,{title:string,placeholder:string,example:string}>)[d.id];const example=entry?.title===d.title?entry:undefined;return <article id={d.id} className={'decision tone-'+tone(d.status)}><div className="decision-number">{String(Number(d.id.split('.').pop())+1).padStart(2,'0')}</div><div className="decision-area"><h3>{d.title}</h3></div><div className="decision-guidance"><p>{d.guidance}</p>{example&&<details className="example-answer"><summary>Example answer</summary><p className="example-note">Illustrative only — adapt to your architecture.</p><p data-example>{example.example}</p></details>}</div><div className="decision-body"><label>Decision<textarea placeholder={example?.placeholder||"Write the architecture decision…"} value={d.decision} onChange={e=>onChange({...d,decision:e.target.value})}/></label><details><summary>Notes</summary><label>Review notes<textarea value={d.notes} onChange={e=>onChange({...d,notes:e.target.value})}/></label></details></div><Field label={`${d.title} status`} value={d.status} options={statuses} onChange={v=>onChange({...d,status:v as Decision['status']})}/></article>;}
export type Column={key:string,label:string,options?:string[],type?:string,placeholder?:string};
export function InventoryTable({title,columns,rows,onChange}:{title:string,columns:Column[],rows:Record<string,string>[],onChange:(rows:Record<string,string>[])=>void}){return <section><h3>{title}</h3><div className="table-wrap"><table><caption>{title} — editable inventory</caption><thead><tr>{columns.map(c=><th key={c.key} scope="col">{c.label}</th>)}<th scope="col">Remove</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}>{columns.map(c=><td key={c.key}>{c.type==='textarea'?<label>{`${c.label} row ${i+1}`}<textarea placeholder={c.placeholder||''} value={r[c.key]||''} onChange={e=>onChange(rows.map((row,j)=>j===i?{...row,[c.key]:e.target.value}:row))}/></label>:<Field label={`${c.label} row ${i+1}`} placeholder={c.placeholder} value={r[c.key]||''} options={c.options} onChange={v=>onChange(rows.map((row,j)=>j===i?{...row,[c.key]:v}:row))}/>}</td>)}<td><button aria-label={`Remove row ${i+1}`} onClick={()=>onChange(rows.filter((_,j)=>j!==i))}>×</button></td></tr>)}</tbody></table></div>{!rows.length&&<p className="muted">No entries yet. Add only resources this agent actually uses.</p>}<button onClick={()=>onChange([...rows,{id:crypto.randomUUID()}])}>Add row</button></section>;}
export function Confirmation({title,onConfirm,onCancel}:{title:string,onConfirm:()=>void,onCancel:()=>void}){return <div className="overlay" onKeyDown={e=>{if(e.key==='Escape')onCancel();if(e.key==='Tab'){const buttons=e.currentTarget.querySelectorAll('button');if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons[1].focus();}else if(!e.shiftKey&&document.activeElement===buttons[1]){e.preventDefault();buttons[0].focus();}}}}><section role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{title}</h2><p>This replaces the current architecture stored in this browser. Export first to keep a copy.</p><button autoFocus onClick={onCancel}>Cancel</button> <button className="danger" onClick={onConfirm}>Replace architecture</button></section></div>;}
